leva/companies/urls.py
from django.urls import path
from .views import detail_company, list_companies,search_companies
from . import views

app_name = 'companies'
urlpatterns = [
    path('', views.list_companies, name='list'),
    path('search/', views.search_companies, name= 'search'),
    path('<int:company_id>/', views.detail_company, name='detail'),
]

leva/landingpage/urls.py
from django.urls import path
from . import views
from .views import Cadastro_empresa, Dados_empresa

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro_empresa/', Cadastro_empresa.as_view(), name='cadastro_empresa'),
    path('dados_empresa/', Dados_empresa.as_view(), name='dados_empresa'),
]

leva/leva/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landingpage.urls')),
    path('companies/', include('companies.urls')),
    path('admin/', admin.site.urls),
]

leva/companies/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.name} - {self.email}'

class Company(models.Model):

    logoURL = models.URLField(max_length=300, null=True, blank=True)
    cnpj = models.IntegerField(default=0)
    tel = models.IntegerField(default=0)
    job = models.CharField(max_length=255, default='Municipal')
    city = models.CharField(max_length=255)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, default=0000)
    score = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user_id.name} from {self.city}'

class Client(models.Model):
    cpf = models.IntegerField(default=0)
    tel = models.IntegerField(default=0)
    city = models.CharField(max_length=255)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user_id.name}'

class Admin(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user_id.name}'

class Request(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    client_id = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    company_id = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.client_id.username} - {self.company_id.user_id.name} ({self.created_at})'


class Review(models.Model):
    rating = models.IntegerField(default=0)
    comment = models.CharField(max_length=255)
    request_id = models.ForeignKey(Request, on_delete=models.CASCADE, default=000)

    def __str__(self):
        return f'{self.request_id.client_id.username} - {self.request_id.company_id.user_id.name} ({self.request_id.created_at}), {self.comment} ({self.rating})'

leva/landingpage/models.py
from django.db import models

leva/landingpage/forms.py
from django import forms
from companies.models import Company, User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('name', 'email')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Nome', 'label': 'alo'}),
            'email': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Nome', 'label': 'alo'}),
        }

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('logoURL', 'cnpj', 'tel', 'job', 'city', 'score')

        widgets = {
            'cnpj': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'cnpj', 'label': 'alo'}),
            'tel': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'tel', 'label': 'alo'}),
            'job': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'job', 'label': 'alo'}),
            'city': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'city', 'label': 'alo'}),
            'logoURL': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Link de uma imagem associada à postagem'}),
        }

leva/companies/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Company
from django.shortcuts import render, get_object_or_404

# Create your views here

def detail_company(request, company_id):
    company = get_object_or_404(Company, pk=company_id)
    context = {'company': company}
    return render(request, 'companies/detail.html', context)

def list_companies(request):
    company_list = Company.objects.all()
    context = {'company_list': company_list}
    return render(request, 'companies/list.html', context)

def search_companies(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        company_list = Company.objects.filter(name__icontains=search_term)
        context = {"company_list": company_list}
    return render(request, 'companies/search.html', context)

leva/landingpage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from companies.models import Company, User
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import UserForm, CompanyForm
from django.urls import reverse_lazy


def index(request):
    context = {}
    return render(request, 'landingpage/index.html', context)

class Cadastro_empresa(CreateView):
    model = User
    form_class = UserForm
    template_name = 'landingpage/cadastro_empresa.html'
    success_url = reverse_lazy('index')

class Dados_empresa(CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'landingpage/dados_empresa.html'
    success_url = reverse_lazy('index')

leva/companies/templates/companies/detail.html
{% extends 'base.html' %}

{% block title %}
{{company.user_id.name}}
{% endblock title %}

{% block content %}
<h2>{{company.user_id.name}}</h2>

<section class="dados-de-filme">
    <ul class="infos">
        <li><h3>infos:</h3></li>
        <li>Cnpj: {{ company.cnpj }}</li>
        <li>Tel: {{ company.tel }}</li>
        <li>Job: {{ company.job }}</li>
        <li>City: {{ company.city }}</li>
        <li>Score: {{ company.score }}</li>
    </ul>
</section>

{% endblock content %}

leva/companies/templates/companies/list.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Empresas</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'companies:search' %}">Filtrar Empresas</a></p>
</section>
{% if company_list %}
<section class="lista-de-cards">
    {% for company in company_list %}
    <article class="card">
        <a href="{% url 'companies:detail' company.id %}">{{company.user_id.name}}</a>
        <p>{{ company.cnpj }} ({{ company.city }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma empresa.</p>
{% endif %}

{% endblock content %}

leva/companies/templates/companies/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Filtro de Empresas por Nome</h2>
<form action="{% url 'companies:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado do Filtro</h2>
{% if company_list %}
<section class="lista-de-cards">
    {% for company in company_list %}
    <article class="card">
        <p>{{ company.cnpj }} ({{ company.city }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma empresa.</p>
{% endif %}

{% endblock content %}

leva/landingpage/templates/landingpage/cadastro_empresa.html
{% extends 'base.html' %}

{% block content %}
<h1>Cadastro de empresa!</h1>
<p>Para solicitar o cadastro da sua empresa é so preencher os dados abaixos!</p>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Publicar</button>

{% endblock content %}

leva/landingpage/templates/landingpage/dados_empresa.html
{% extends 'base.html' %}

{% block content %}
<h1>Cadastro de empresa!</h1>
<p>Insira os dados da empresa abaixo!</p>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success">Criar</button>

{% endblock content %}

leva/landingpage/templates/landingpage/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Bem Vindo!</h1>
<p>A leva lá faz um monte de coisa!</p>
<h2>Requisitar cadastro de empresa!</h2>
<a href="{% url 'cadastro_empresa' %}">Como se cadastrar</a>

{% endblock content %}

leva/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.png' %}" width="100"> </a>
        <nav id="navegacao-principal">
            <ul><li><a href="{% url 'companies:list' %}">Cadastre-se</a>
                <li><a href="{% url 'companies:list' %}">Logar</a></li>
                <li><a href="{% url 'companies:list' %}">Buscar empresas</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>